import gradio as gr
import requests
import os
import base64
from pypdf import PdfReader
from PIL import Image
import io

HF_TOKEN = os.environ.get("HF_TOKEN", "")

US_STATES = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
    "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
    "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
    "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
    "New Hampshire", "New Jersey", "New Mexico", "New York",
    "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
    "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
    "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
    "West Virginia", "Wisconsin", "Wyoming"
]

VEHICLE_CLASSES = [
    "Economy/Compact (e.g. Toyota Corolla, Honda Civic)",
    "Mid-Size Sedan (e.g. Toyota Camry, Honda Accord)",
    "Full-Size Sedan (e.g. Chevrolet Impala)",
    "Luxury Sedan (e.g. BMW 5 Series, Mercedes E-Class)",
    "Compact SUV (e.g. Toyota RAV4, Honda CR-V)",
    "Mid-Size SUV (e.g. Ford Explorer, Chevrolet Traverse)",
    "Full-Size SUV (e.g. Chevrolet Suburban, Ford Expedition)",
    "Luxury SUV (e.g. Cadillac Escalade, Lincoln Navigator)",
    "Pickup Truck - Standard (e.g. Ford F-150, Chevy Silverado)",
    "Pickup Truck - Heavy Duty (e.g. Ford F-250, Ram 2500)",
    "Minivan (e.g. Honda Odyssey, Chrysler Pacifica)",
    "Sports Car (e.g. Ford Mustang, Chevrolet Camaro)",
    "Electric Vehicle (e.g. Tesla Model 3, Chevy Bolt)"
]

DISCLAIMER_TOP = """
> **⚠️ PRIVACY NOTICE**: Remove ALL personally identifiable information (PII) before uploading documents.
> This includes names, addresses, phone numbers, SSNs, policy/claim numbers, VINs, and license plates.
> By uploading, you confirm all PII has been removed. See our [Privacy Policy](https://quantusdata.ai/privacy.html).
"""

DISCLAIMER = """
> **LEGAL DISCLAIMER**: This tool is powered by Artificial Intelligence and is intended
> for informational and arbitration preparation purposes only. All results, analyses,
> contentions, and recommendations generated by this application are AI-generated and
> should be reviewed by a licensed insurance professional, attorney, or qualified claims
> expert before use in actual arbitration proceedings. This tool does not constitute
> legal or professional advice. State laws and insurance regulations change frequently.
> The developers assume no liability for decisions made based on this tool's output.
> © 2026 Existential Gateway, LLC. All Rights Reserved. Proprietary Software.
"""

WAIT_MSG = "*Results take approximately 1-2 minutes to generate. Please do not click multiple times.*"

WATERMARK = """
---
© 2026 Existential Gateway, LLC | AI Insurance Arbitration Assistant
Unauthorized reproduction, distribution, or commercial use of this output
or the underlying software is strictly prohibited.
For licensing inquiries: existentialgateway@gmail.com
Visit us at: https://existentialgateway.com
---
"""

PII_REPAIR = """
> **PERSONAL INFORMATION NOTICE**: Before uploading any documents, you MUST redact:
> Insured Name | Address | Phone Number | Email | Driver License | VIN Number | Policy Number | Claim Number | SSN
> VIN numbers can identify vehicle owners and must be redacted for privacy.
> By uploading you confirm all personal information has been removed.
"""

PII_RENTAL = """
> **PERSONAL INFORMATION NOTICE**: Before uploading any documents, you MUST redact:
> Insured Name | Address | Phone Number | Email | Driver License | VIN Number | Policy Number | Claim Number | Credit Card Info
> By uploading you confirm all personal information has been removed.
"""

PII_TL = """
> **PERSONAL INFORMATION NOTICE**: Before uploading any documents, you MUST redact:
> Insured Name | Address | Phone Number | Email | Driver License | VIN Number | Policy Number | Claim Number | SSN | Bank Account Info
> VIN numbers can identify vehicle owners and must be redacted for privacy.
> By uploading you confirm all personal information has been removed.
"""

PII_BI = """
> **HIPAA NOTICE**: Medical records contain Protected Health Information (PHI) subject to HIPAA regulations.
> Before uploading you MUST redact: Patient Name | Date of Birth | SSN | Address | Phone | Email | Member ID
> Upload only treatment dates, diagnosis codes, procedure codes, and billing amounts.
> This platform is NOT a HIPAA-compliant environment. Never upload unredacted medical records.
"""

PII_LIAB = """
> **PERSONAL INFORMATION NOTICE**: Before uploading photos or entering details, you MUST exclude:
> Insured Name | Address | Phone Number | Policy Number | Claim Number | Driver License | License Plate Numbers
> Do not include personally identifiable information in the loss description field.
"""

PII_CHAT = """
> **DOCUMENT PRIVACY NOTICE**: Before uploading any documents for AI Chat, you MUST redact ALL
> personally identifiable information including: Names | Addresses | Phone Numbers | SSN |
> VIN Numbers | Policy Numbers | Claim Numbers | Medical Record Numbers | Financial Account Numbers.
> This platform is NOT HIPAA compliant. Never upload unredacted sensitive documents.
> By uploading you confirm all personal information has been removed.
"""


def fetch_url_content(text):
    """Detect URLs in user text, fetch their content, and return as context."""
    import re
    urls = re.findall(r'https?://[^\s<>"{}|\^`\[\]]+', text)
    if not urls:
        return ""
    fetched = []
    for url in urls[:3]:  # limit to 3 URLs
        try:
            headers = {
                "User-Agent": "Mozilla/5.0 (compatible; ExistentialGateway/1.0)",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
            }
            r = requests.get(url, timeout=15, headers=headers)
            if r.status_code == 200:
                from html.parser import HTMLParser
                class TextExtractor(HTMLParser):
                    def __init__(self):
                        super().__init__()
                        self.text = []
                        self.skip = False
                    def handle_starttag(self, tag, attrs):
                        if tag in ('script', 'style', 'nav', 'footer', 'header'):
                            self.skip = True
                    def handle_endtag(self, tag):
                        if tag in ('script', 'style', 'nav', 'footer', 'header'):
                            self.skip = False
                    def handle_data(self, data):
                        if not self.skip and data.strip():
                            self.text.append(data.strip())
                parser = TextExtractor()
                parser.feed(r.text)
                page_text = ' '.join(parser.text)[:3000]
                fetched.append(f"[URL: {url}]\n{page_text}")
        except Exception as e:
            fetched.append(f"[URL: {url}] Could not fetch: {str(e)}")
    if fetched:
        return "\n\nUSER-PROVIDED URL CONTENT (analyze this as part of your response):\n" + "\n---\n".join(fetched)
    return ""



def enrich_with_urls(text):
    """If text contains URLs, fetch and append their content."""
    if not text or 'http' not in text:
        return text
    url_content = fetch_url_content(text)
    if url_content:
        return text + url_content
    return text


def query_llm(prompt):
    API_KEY = os.environ.get("OPENAI_API_KEY", "")
    headers = {"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/json"}
    msgs = messages if 'messages' in dir() else [{"role": "user", "content": prompt}]
    payload = {"model": "gpt-4o", "max_tokens": 4000, "messages": msgs}
    try:
        response = requests.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload, timeout=240)
        result = response.json()
        if "choices" in result:
            return result["choices"][0]["message"]["content"]
        return f"API Error: {result}"
    except Exception as e:
        return f"Error: {str(e)}"

def query_vision(prompt, images):
    API_KEY = os.environ.get("OPENAI_API_KEY", "")
    headers = {"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/json"}
    content_parts = [{"type": "text", "text": "You are looking at real images attached to this message. You CAN see them. Analyze them thoroughly.\n\n" + prompt}]
    for img in images:
        try:
            pil_img = None
            if isinstance(img, Image.Image):
                pil_img = img
            elif isinstance(img, str) and os.path.isfile(img):
                pil_img = Image.open(img)
            elif hasattr(img, "name") and os.path.isfile(getattr(img, "name", "")):
                pil_img = Image.open(img.name)
            elif isinstance(img, dict) and "path" in img:
                pil_img = Image.open(img["path"])
            else:
                continue
            if pil_img.mode in ("RGBA", "P", "LA"):
                pil_img = pil_img.convert("RGB")
            if max(pil_img.size) > 1024:
                pil_img.thumbnail((1024, 1024))
            buf = io.BytesIO()
            pil_img.save(buf, format="JPEG", quality=85)
            b64 = base64.b64encode(buf.getvalue()).decode("utf-8")
            content_parts.append({
                "type": "image_url",
                "image_url": {"url": "data:image/jpeg;base64," + b64}
            })
        except Exception:
            continue
    msgs = [{"role": "user", "content": content_parts}]
    payload = {"model": "gpt-4o", "max_tokens": 4000, "messages": msgs}
    try:
        response = requests.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload, timeout=240)
        result = response.json()
        if "choices" in result:
            return result["choices"][0]["message"]["content"]
        return "API Error: " + str(result)
    except Exception as e:
        return "Error: " + str(e)

def extract_pdf_text(pdf_file):
    if pdf_file is None:
        return ""
    try:
        if pdf_file.name.lower().endswith(('.jpg', '.jpeg', '.png', '.webp')):
            return f"[Image document uploaded: {pdf_file.name}]"
        reader = PdfReader(pdf_file.name)
        text = ""
        for page in reader.pages:
            extracted = page.extract_text()
            if extracted:
                text += extracted + "\n"
        return text.strip()
    except Exception as e:
        return f"Error reading file: {str(e)}"

def analyze_repair_estimate(
    estimate_pdf, no_estimate,
    photo1, photo2, photo3, photo4, photo5, photo6,
    loss_state, repair_state,
    vehicle_year, vehicle_make, vehicle_model
):
    results = ["# REPAIR ESTIMATE ANALYSIS\n", DISCLAIMER + "\n"]
    estimate_text = extract_pdf_text(estimate_pdf) if estimate_pdf and not no_estimate else ""
    has_estimate = bool(estimate_text)

    if not has_estimate and not no_estimate:
        return "Please either upload a repair estimate PDF or check No estimate written."

    photos = [p for p in [photo1, photo2, photo3, photo4, photo5, photo6] if p is not None]

    if not photos and not has_estimate:
        return "Please upload at least one damage photo or a repair estimate."

    photo_analysis = ""
    if photos:
        photo_prompt = (
            "You are an expert automotive damage appraiser with 20 years experience. Write as the professional analyst who performed this work. State all findings directly with specific numbers, percentages, and comparisons. NEVER say 'this appears to be', 'the data seems to show', 'the dataset contains', or 'it looks like'. Instead, deliver results confidently: 'Average claim cost was $4,230, a 12% increase year-over-year' or 'Readmission rates of 18.3% in Cardiology exceeded the facility average by 4.1 percentage points.' Be direct, precise, and actionable. Present findings as YOUR analysis, not a description of a dataset. "
            "I have attached damage photos directly to this message as images. You MUST analyze the actual visible damage shown in these attached images. "
            "These are real photos of a " + vehicle_year + " " + vehicle_make + " " + vehicle_model + ". "
            "Do NOT say you cannot see images. The images ARE attached and visible to you. Describe the specific damage you observe. "
            "Provide: 1) Detailed description of visible damage for each area "
            "2) Which panels and parts are damaged "
            "3) Severity of damage (minor, moderate, severe) "
            "4) Whether damage appears consistent with a collision "
            "5) Any pre-existing damage noted "
            "6) Whether vehicle appears to be a total loss "
            "7) Estimated repair complexity"
        )
        photo_analysis = query_vision(photo_prompt, photos)
        results.append("## PHOTO DAMAGE ANALYSIS\n")
        results.append(photo_analysis + "\n\n")

    estimate_section = estimate_text[:3000] if has_estimate else "No repair estimate provided - vehicle may be an obvious total loss. Base analysis on photo damage assessment only."

    prompt = (
        "You are an expert insurance claims adjuster and automotive repair specialist. Write as the professional analyst who performed this work. State all findings directly with specific numbers, percentages, and comparisons. NEVER say 'this appears to be', 'the data seems to show', 'the dataset contains', or 'it looks like'. Instead, deliver results confidently: 'Average claim cost was $4,230, a 12% increase year-over-year' or 'Readmission rates of 18.3% in Cardiology exceeded the facility average by 4.1 percentage points.' Be direct, precise, and actionable. Present findings as YOUR analysis, not a description of a dataset. \n\n"
        "Vehicle: " + vehicle_year + " " + vehicle_make + " " + vehicle_model + "\n"
        "Loss State: " + loss_state + "\n"
        "Repair State: " + repair_state + "\n"
        "Estimate Available: " + ("Yes" if has_estimate else "No - Obvious Total Loss") + "\n\n"
        "REPAIR ESTIMATE:\n" + estimate_section + "\n\n"
        "PHOTO DAMAGE ASSESSMENT:\n" + (photo_analysis[:500] if photo_analysis else "No photos provided") + "\n\n"
        "Provide this exact analysis with ALL sections completed:\n\n"
        "## 1. VEHICLE VERIFICATION\n"
        "STEP 1 - YEAR: Does year on estimate match " + vehicle_year + "? MATCH or MISMATCH\n"
        "STEP 2 - MAKE: Does make on estimate match " + vehicle_make + "? MATCH or MISMATCH\n"
        "STEP 3 - MODEL: Does model on estimate match " + vehicle_model + "? MATCH or MISMATCH\n"
        "STEP 4 - COLOR: Does color on estimate match color in photos? MATCH, MISMATCH, or UNABLE TO CONFIRM\n"
        "STEP 5 - DAMAGE: Do damaged areas on estimate match photos? MATCH, MISMATCH, or PARTIAL MATCH\n"
        "OVERALL: VERIFIED, NOT VERIFIED, or UNABLE TO FULLY VERIFY\n\n"
        "## 2. REASONABLE REPAIRS\n"
        "List each repair operation that is reasonable and justified.\n\n"
        "## 3. DISPUTED OPERATIONS\n"
        "List each operation that appears unnecessary, overpriced, or not supported by photos.\n\n"
        "## 4. LABOR RATE ANALYSIS — MARKET RATE EVIDENCE\n"
        "You MUST provide specific market rate evidence for " + repair_state + ":\n"
        "A. State the EXACT labor rates on the estimate (body, mechanical, paint, frame — each separately).\n"
        "B. Research and cite the current prevailing labor rates in " + repair_state + " by category:\n"
        "| Labor Type | Estimate Rate | " + repair_state + " Market Average | Source |\n"
        "|------------|--------------|----------------------|--------|\n"
        "| Body Labor | $XX/hr | $XX/hr | CCC/Mitchell/Audatex prevailing rate |\n"
        "| Paint Labor | $XX/hr | $XX/hr | CCC/Mitchell/Audatex prevailing rate |\n"
        "| Mechanical Labor | $XX/hr | $XX/hr | CCC/Mitchell/Audatex prevailing rate |\n"
        "| Frame Labor | $XX/hr | $XX/hr | CCC/Mitchell/Audatex prevailing rate |\n"
        "C. Reference DEG (Database Enhancement Gateway) for labor time disputes.\n"
        "D. Reference " + repair_state + " DOI (Department of Insurance) rate surveys or guidelines if applicable.\n"
        "E. State whether each rate is ABOVE, BELOW, or AT market rate and by how much.\n"
        "F. If recommending different rates, show the EXACT calculation with market data supporting it.\n\n"
        "## 5. PARTS ANALYSIS — MARKET PRICING EVIDENCE\n"
        "You MUST provide specific parts pricing evidence:\n"
        "A. List EACH part on the estimate with its price and whether it is OEM, aftermarket (AM), recycled/LKQ, or reconditioned.\n"
        "B. For each part, provide market comparison:\n"
        "| Part Name | Estimate Price | OEM Price | AM Price | LKQ Price | Type Used | Reasonable? |\n"
        "|-----------|---------------|-----------|----------|-----------|-----------|-------------|\n"
        "C. Cite " + loss_state + " regulations on aftermarket parts usage (consent requirements, age/mileage thresholds).\n"
        "D. Cite " + loss_state + " regulations on LKQ/recycled parts (quality standards, warranties required).\n"
        "E. For disputed parts: state the exact price difference and cite the regulation that supports your position.\n"
        "F. Reference OEM position statements for any safety-related parts (airbags, structural, ADAS).\n"
        "G. Note any parts where the estimate markup exceeds the typical 25-35% dealer markup.\n\n"
        "## 6. TOTAL LOSS EVALUATION\n"
        "TOTAL LOSS THRESHOLD: State exact percentage for " + loss_state + "\n"
        "ESTIMATED ACV: $[amount for " + vehicle_year + " " + vehicle_make + " " + vehicle_model + "]\n"
        "TOTAL REPAIR COST: $[from estimate]\n"
        "LOSS RATIO: repair cost divided by ACV = X percent\n"
        "THRESHOLD MET: YES or NO\n"
        "DETERMINATION: SHOULD HAVE BEEN DECLARED A TOTAL LOSS or REPAIRS WERE REASONABLE\n"
        "STATUTE: cite exact " + loss_state + " total loss statute\n\n"
        "## 7. ARBITRATION CONTENTIONS\n"
        "For EACH disputed item provide: operation name, dollar amount, detailed contention, citation\n\n"
        "## 8. RECOMMENDED ADJUSTMENTS\n"
        "Itemized list with original amount, recommended amount, reduction\n"
        "TOTAL REDUCTION: $X\n"
        "RECOMMENDED PAYMENT: $X"
    )

    results.append("## ESTIMATE ANALYSIS AND ARBITRATION CONTENTIONS\n")
    results.append(query_llm(prompt))
    results.append(WATERMARK)
    return "\n".join(results)

def analyze_rental(
    rental_pdf, repair_pdf,
    vehicle_class, loss_state, repair_state,
    repair_start_date, repair_end_date
):
    results = ["# RENTAL BILL ANALYSIS\n", DISCLAIMER + "\n"]
    rental_text = extract_pdf_text(rental_pdf)
    repair_text = extract_pdf_text(repair_pdf) if repair_pdf else "No repair estimate provided"

    if not rental_text:
        return "Please upload a valid rental bill PDF."

    prompt = (
        "You are an expert insurance claims adjuster specializing in rental reimbursement. Write as the professional analyst who performed this work. State all findings directly with specific numbers, percentages, and comparisons. NEVER say 'this appears to be', 'the data seems to show', 'the dataset contains', or 'it looks like'. Instead, deliver results confidently: 'Average claim cost was $4,230, a 12% increase year-over-year' or 'Readmission rates of 18.3% in Cardiology exceeded the facility average by 4.1 percentage points.' Be direct, precise, and actionable. Present findings as YOUR analysis, not a description of a dataset. \n\n"
        "Loss State: " + loss_state + "\n"
        "Repair State: " + repair_state + "\n"
        "Vehicle Class: " + vehicle_class + "\n"
        "Repair Period: " + repair_start_date + " to " + repair_end_date + "\n\n"
        "RENTAL BILL:\n" + rental_text[:2000] + "\n\n"
        "REPAIR ESTIMATE:\n" + repair_text[:1500] + "\n\n"
        "## 1. REPAIR TIME ASSESSMENT\n"
        "Reasonable repair time for " + vehicle_class + " using Mitchell labor times.\n\n"
        "## 2. RENTAL RATE ANALYSIS — MARKET RATE EVIDENCE\n"
        "You MUST provide specific market rate evidence to justify your recommended daily rate.\n"
        "A. State the EXACT daily rate charged on the rental bill.\n"
        "B. Research and cite the current average daily rental rate for a " + vehicle_class + " in " + repair_state + " from major rental companies (Enterprise, Hertz, Avis, Budget, National).\n"
        "C. Provide a comparison table:\n"
        "| Rental Company | Vehicle Class | Daily Rate | Source |\n"
        "|----------------|--------------|------------|--------|\n"
        "| Enterprise | " + vehicle_class + " | $XX/day | Enterprise.com market rate |\n"
        "| Hertz | " + vehicle_class + " | $XX/day | Hertz.com market rate |\n"
        "| Budget | " + vehicle_class + " | $XX/day | Budget.com market rate |\n"
        "| AVERAGE | " + vehicle_class + " | $XX/day | Calculated average |\n"
        "D. State whether the billed rate is ABOVE, BELOW, or AT market rate.\n"
        "E. If recommending a different rate, explain EXACTLY how you calculated it using the market data above.\n"
        "F. Reference " + repair_state + " direct payment and prevailing rate guidelines if applicable.\n\n"
        "## 3. DISPUTED RENTAL DAYS\n"
        "Reasonable days vs disputed days and why.\n\n"
        "## 4. LOSS OF USE ANALYSIS\n"
        "Per " + loss_state + " statutes - applicable? Reasonable amount?\n\n"
        "## 5. ARBITRATION CONTENTIONS\n"
        "Arguments for each disputed day with " + loss_state + " statutory citations.\n\n"
        "## 6. RECOMMENDED ADJUSTMENT\n"
        "Reasonable days, daily rate, total reasonable rental, amount to dispute."
    )

    results.append(query_llm(prompt))
    results.append(WATERMARK)
    return "\n".join(results)

def analyze_total_loss(
    valuation_pdf, estimate_pdf,
    vehicle_year, vehicle_make, vehicle_model, vehicle_trim,
    vehicle_mileage, loss_date, loss_state,
    market_zip, condition
):
    results = ["# TOTAL LOSS ANALYSIS\n", DISCLAIMER + "\n"]
    valuation_text = extract_pdf_text(valuation_pdf)
    estimate_text = extract_pdf_text(estimate_pdf) if estimate_pdf else ""

    if not valuation_text:
        return "Please upload a valid valuation report PDF."

    prompt = (
        "You are an expert total loss adjuster and vehicle valuation specialist. Write as the professional analyst who performed this work. State all findings directly with specific numbers, percentages, and comparisons. NEVER say 'this appears to be', 'the data seems to show', 'the dataset contains', or 'it looks like'. Instead, deliver results confidently: 'Average claim cost was $4,230, a 12% increase year-over-year' or 'Readmission rates of 18.3% in Cardiology exceeded the facility average by 4.1 percentage points.' Be direct, precise, and actionable. Present findings as YOUR analysis, not a description of a dataset. \n\n"
        "Vehicle: " + vehicle_year + " " + vehicle_make + " " + vehicle_model + " " + vehicle_trim + "\n"
        "Mileage: " + vehicle_mileage + "\n"
        "Loss Date: " + loss_date + "\n"
        "Loss State: " + loss_state + "\n"
        "Market Area ZIP: " + market_zip + "\n"
        "Vehicle Condition: " + condition + "\n\n"
        "VALUATION REPORT:\n" + valuation_text[:3000] + "\n\n"
        "REPAIR ESTIMATE:\n" + (estimate_text[:1000] if estimate_text else "No estimate - obvious total loss") + "\n\n"
        "## 1. TOTAL LOSS THRESHOLD ANALYSIS\n"
        + loss_state + " total loss threshold, repair cost vs ACV, cite statutes.\n\n"
        "## 2. ACTUAL CASH VALUE ANALYSIS\n"
        "Is proposed ACV reasonable? Any disputed adjustments?\n\n"
        "## 3. COMPARABLE VEHICLE ANALYSIS\n"
        "3 comparable vehicles in " + market_zip + " area around " + loss_date + ".\n\n"
        "## 4. REFURBISHMENT ANALYSIS\n"
        "Are claimed refurbishments legitimate and values reasonable?\n\n"
        "## 5. LOSS OF USE\n"
        "Per " + loss_state + " statutes - applicable for total loss?\n\n"
        "## 6. SETTLEMENT REASONABLENESS\n"
        "Is proposed settlement reasonable? Recommended adjustments.\n\n"
        "## 7. ARBITRATION CONTENTIONS\n"
        "Arguments for each disputed element citing " + loss_state + " total loss statutes."
    )

    results.append(query_llm(prompt))
    results.append(WATERMARK)
    return "\n".join(results)

def analyze_bodily_injury(
    medical_pdf, photo1, photo2, photo3, photo4,
    loss_state, impact_description,
    vehicle1_damage_areas, vehicle2_damage_areas,
    impact_speed_estimate
):
    results = ["# BODILY INJURY ANALYSIS\n", DISCLAIMER + "\n"]
    medical_text = extract_pdf_text(medical_pdf) if medical_pdf else ""
    photos = [p for p in [photo1, photo2, photo3, photo4] if p is not None]

    impact_analysis = ""
    if photos:
        photo_prompt = (
            "You are an expert accident reconstructionist and biomechanical analyst. Write as the professional analyst who performed this work. State all findings directly with specific numbers, percentages, and comparisons. NEVER say 'this appears to be', 'the data seems to show', 'the dataset contains', or 'it looks like'. Instead, deliver results confidently: 'Average claim cost was $4,230, a 12% increase year-over-year' or 'Readmission rates of 18.3% in Cardiology exceeded the facility average by 4.1 percentage points.' Be direct, precise, and actionable. Present findings as YOUR analysis, not a description of a dataset. "
            "I have attached collision damage photos directly to this message as images. You MUST analyze the actual visible damage shown in these attached images. "
            "Do NOT say you cannot see images. The images ARE attached and visible to you. "
            "Analyze the attached collision damage photos for: "
            "1) Severity of impact 2) Direction of force "
            "3) Estimated delta-V from damage pattern "
            "4) Whether damage is consistent with reported injuries. "
            "Impact: " + impact_description + " "
            "V1 Damage: " + vehicle1_damage_areas + " "
            "V2 Damage: " + vehicle2_damage_areas + " "
            "Speed: " + impact_speed_estimate
        )
        impact_analysis = query_vision(photo_prompt, photos)
        results.append("## IMPACT ANALYSIS\n")
        results.append(impact_analysis + "\n\n")

    if not medical_text and not photos:
        return "Please upload medical records or damage photos."

    if medical_text:
        prompt = (
            "You are an expert insurance claims adjuster specializing in bodily injury. Write as the professional analyst who performed this work. State all findings directly with specific numbers, percentages, and comparisons. NEVER say 'this appears to be', 'the data seems to show', 'the dataset contains', or 'it looks like'. Instead, deliver results confidently: 'Average claim cost was $4,230, a 12% increase year-over-year' or 'Readmission rates of 18.3% in Cardiology exceeded the facility average by 4.1 percentage points.' Be direct, precise, and actionable. Present findings as YOUR analysis, not a description of a dataset. \n\n"
            "Loss State: " + loss_state + "\n"
            "Impact: " + impact_description + "\n"
            "Speed: " + impact_speed_estimate + "\n"
            "IMPACT ASSESSMENT: " + (impact_analysis[:500] if impact_analysis else "No photos") + "\n"
            "MEDICAL RECORDS: " + medical_text[:3000] + "\n\n"
            "## 1. INJURY REASONABLENESS\n"
            "Are injuries consistent with impact severity?\n\n"
            "## 2. TREATMENT REASONABLENESS\n"
            "Is treatment plan reasonable? Any excessive treatment?\n\n"
            "## 3. MEDICAL BILL ANALYSIS\n"
            "Are charges within " + loss_state + " medical fee schedules?\n\n"
            "## 4. CAUSATION ANALYSIS\n"
            "Which injuries are causally related? Pre-existing conditions?\n\n"
            "## 5. " + loss_state + " SPECIFIC REQUIREMENTS\n"
            "PIP/MedPay, threshold requirements, relevant statutes.\n\n"
            "## 6. ARBITRATION CONTENTIONS\n"
            "Arguments citing biomechanics, medical necessity, and statutes.\n\n"
            "## 7. RECOMMENDED SETTLEMENT RANGE\n"
            "Special damages, general damages, total recommended range."
        )
        results.append("## MEDICAL ANALYSIS\n")
        results.append(query_llm(prompt))
        results.append(WATERMARK)

    return "\n".join(results)

def analyze_liability(
    loss_state, intersection, city,
    num_vehicles, vehicle1_direction, vehicle1_damage_areas,
    vehicle2_direction, vehicle2_damage_areas,
    vehicle3_direction, vehicle3_damage_areas,
    loss_description, traffic_controls,
    photo1, photo2, photo3, photo4,
    photo5=None, photo6=None, photo7=None, photo8=None,
    police_report=None, additional_doc=None, adverse_statement=None
):
    results = ["# LIABILITY AND ACCIDENT RECONSTRUCTION\n", DISCLAIMER + "\n"]
    photos = [p for p in [photo1, photo2, photo3, photo4, photo5, photo6, photo7, photo8] if p is not None]

    scene_analysis = ""
    if photos:
        photo_prompt = (
            "You are an expert accident reconstructionist. Write as the professional analyst who performed this work. State all findings directly with specific numbers, percentages, and comparisons. NEVER say 'this appears to be', 'the data seems to show', 'the dataset contains', or 'it looks like'. Instead, deliver results confidently: 'Average claim cost was $4,230, a 12% increase year-over-year' or 'Readmission rates of 18.3% in Cardiology exceeded the facility average by 4.1 percentage points.' Be direct, precise, and actionable. Present findings as YOUR analysis, not a description of a dataset. "
            "I have attached accident scene and damage photos directly to this message as images. You MUST analyze the actual visible damage shown in these attached images. "
            "Do NOT say you cannot see images. The images ARE attached and visible to you. "
            "Analyze the attached accident scene and damage photos for: "
            "1) Vehicle positions and directions 2) Point of impact "
            "3) Physical evidence of fault 4) Road conditions "
            "5) Traffic control compliance. "
            "Location: " + intersection + ", " + city + ", " + loss_state + " "
            "V1: " + vehicle1_direction + " damage: " + vehicle1_damage_areas + " "
            "V2: " + vehicle2_direction + " damage: " + vehicle2_damage_areas + " "
            "Traffic: " + traffic_controls
        )
        scene_analysis = query_vision(photo_prompt, photos)
        results.append("## SCENE AND DAMAGE ANALYSIS\n")
        results.append(scene_analysis + "\n\n")

    police_text = extract_pdf_text(police_report) if police_report else ""
    insured_statement_text = extract_pdf_text(additional_doc) if additional_doc else ""
    adverse_statement_text = extract_pdf_text(adverse_statement) if adverse_statement else ""
    doc_section = ""
    if police_text:
        doc_section += "POLICE REPORT:\n" + police_text[:2000] + "\n\n"
    if insured_statement_text:
        doc_section += "RECORDED STATEMENT - INSURED PARTY:\n" + insured_statement_text[:1000] + "\n\n"
    if adverse_statement_text:
        doc_section += "RECORDED STATEMENT - ADVERSE PARTY:\n" + adverse_statement_text[:1000] + "\n\n"

    v3_info = ""
    if num_vehicles == "3":
        v3_info = "\nVehicle 3 Direction: " + vehicle3_direction + "\nVehicle 3 Damage: " + vehicle3_damage_areas

    prompt = (
        "You are an expert insurance claims adjuster and accident reconstructionist. Write as the professional analyst who performed this work. State all findings directly with specific numbers, percentages, and comparisons. NEVER say 'this appears to be', 'the data seems to show', 'the dataset contains', or 'it looks like'. Instead, deliver results confidently: 'Average claim cost was $4,230, a 12% increase year-over-year' or 'Readmission rates of 18.3% in Cardiology exceeded the facility average by 4.1 percentage points.' Be direct, precise, and actionable. Present findings as YOUR analysis, not a description of a dataset. \n\n"
        "Loss Location: " + intersection + ", " + city + ", " + loss_state + "\n"
        "Loss State: " + loss_state + "\n"
        "Number of Vehicles: " + num_vehicles + "\n"
        "Traffic Controls: " + traffic_controls + "\n\n"
        "Vehicle 1 OUR INSURED: Direction: " + vehicle1_direction + " | Damage: " + vehicle1_damage_areas + "\n"
        "Vehicle 2 ADVERSE: Direction: " + vehicle2_direction + " | Damage: " + vehicle2_damage_areas + "\n"
        + v3_info + "\n\n"
        "Loss Description: " + loss_description + "\n\n"
        "SCENE ANALYSIS: " + (scene_analysis[:500] if scene_analysis else "No photos") + "\n\n"
        + doc_section +
        "## 1. ACCIDENT RECONSTRUCTION\n"
        "Detailed reconstruction based on damage patterns and physics.\n\n"
        "## 2. TRAFFIC LAW ANALYSIS\n"
        "Per " + loss_state + " Vehicle Code: applicable laws, right of way, violations.\n\n"
        "## 3. WHY VEHICLE 1 IS NOT AT FAULT\n"
        "Lawful actions, physical evidence, how Vehicle 2 negligence caused collision.\n\n"
        "## 4. WHY VEHICLE 2 IS AT FAULT\n"
        "Negligent acts, traffic violations, proximate cause, physical evidence.\n\n"
        "## 5. COMPARATIVE NEGLIGENCE\n"
        "Per " + loss_state + " laws: fault standard, recommended allocation.\n\n"
        "## 6. COMPLETE ARBITRATION ARGUMENT\n"
        "Opening statement, key arguments, evidence, legal citations.\n\n"
        "## 7. RECOMMENDED LIABILITY POSITION\n"
        "Fault split, strongest arguments, weaknesses to address."
    )

    results.append("## LIABILITY ANALYSIS AND CONTENTIONS\n")
    results.append(query_llm(prompt))
    results.append(WATERMARK)
    return "\n".join(results)

def chat_with_documents(
    message,
    doc1=None, doc2=None, doc3=None, doc4=None,
    chat_context="",
    history=None
):
    if history is None:
        history = []
    if not message:
        return history, ""

    doc_texts = []
    doc_labels = ["Document 1", "Document 2", "Document 3", "Document 4"]
    docs = [doc1, doc2, doc3, doc4]

    for i, doc in enumerate(docs):
        if doc is not None:
            text = extract_pdf_text(doc)
            if text:
                doc_texts.append(f"=== {doc_labels[i]} ({doc.name}) ===\n{text[:2000]}")

    img_docs = []
    for doc in docs:
        if doc is not None and doc.name.lower().endswith(('.jpg', '.jpeg', '.png', '.webp')):
            try:
                img = Image.open(doc.name)
                img_docs.append(img)
            except:
                pass

    combined_docs = "\n\n".join(doc_texts) if doc_texts else ""
    context_info = "Additional context: " + chat_context if chat_context.strip() else ""

    conv_history = ""
    if history:
        for h in history[-3:]:
            conv_history += f"User: {h[0]}\nAssistant: {h[1]}\n\n"

    if img_docs and not doc_texts:
        vision_prompt = (
            "You are an expert insurance professional AI assistant. Write as the professional analyst who performed this work. State all findings directly with specific numbers, percentages, and comparisons. NEVER say 'this appears to be', 'the data seems to show', 'the dataset contains', or 'it looks like'. Instead, deliver results confidently: 'Average claim cost was $4,230, a 12% increase year-over-year' or 'Readmission rates of 18.3% in Cardiology exceeded the facility average by 4.1 percentage points.' Be direct, precise, and actionable. Present findings as YOUR analysis, not a description of a dataset. "
            "Previous conversation:\n" + conv_history +
            "\nContext: " + context_info +
            "\n\nUser question: " + message +
            "\n\nProvide a detailed, professional insurance analysis response."
        )
        response = query_vision(vision_prompt, img_docs)
    elif combined_docs:
        prompt = (
            "You are an expert insurance professional AI assistant specializing in "
            "claims analysis, arbitration, total loss, bodily injury, and liability.\n\n"
            "UPLOADED DOCUMENTS:\n" + combined_docs + "\n\n"
            + context_info + "\n\n"
            "CONVERSATION HISTORY:\n" + conv_history +
            "User: " + message + "\n\n"
            "Provide a detailed, professional response based on the uploaded documents."
        )
        response = query_llm(prompt)
    else:
        prompt = (
            "You are an expert insurance professional AI assistant specializing in "
            "claims analysis, arbitration, total loss, bodily injury, and liability.\n\n"
            + context_info + "\n\n"
            "CONVERSATION HISTORY:\n" + conv_history +
            "User: " + message + "\n\n"
            "Provide a detailed, professional insurance response."
        )
        response = query_llm(prompt)

    response += "\n\n" + WATERMARK
    history.append({"role": "user", "content": message})
    history.append({"role": "assistant", "content": response})
    return history, ""

# Gradio UI
with gr.Blocks(title="AI Insurance Arbitration Assistant", theme=gr.themes.Base(
        primary_hue=gr.themes.colors.Color(
            c50="#fef9ec", c100="#faefd0", c200="#f4dea0", c300="#edc970",
            c400="#e4b04a", c500="#c9a84c", c600="#a8872e", c700="#856519",
            c800="#5e440d", c900="#3a2a05", c950="#1e1502"
        ),
        secondary_hue=gr.themes.colors.Color(
            c50="#e8edf5", c100="#c5d0e6", c200="#9eb0d4", c300="#7490c2",
            c400="#4f74b0", c500="#2d5a9e", c600="#1a3a6e", c700="#112240",
            c800="#0a1628", c900="#060e1a", c950="#03070d"
        ),
        neutral_hue=gr.themes.colors.Color(
            c50="#f0f2f7", c100="#d8dde9", c200="#b8c2d6", c300="#95a3be",
            c400="#7285a6", c500="#536890", c600="#3a4f73", c700="#263856",
            c800="#162438", c900="#0c1622", c950="#060b11"
        ),
        font=gr.themes.GoogleFont("DM Sans"),
        font_mono=gr.themes.GoogleFont("DM Mono"),
    ).set(
        body_background_fill="#0a1628",
        body_background_fill_dark="#0a1628",
        body_text_color="#f8f9fc",
        body_text_color_dark="#f8f9fc",
        block_background_fill="#112240",
        block_background_fill_dark="#112240",
        block_border_color="rgba(201,168,76,0.2)",
        block_border_color_dark="rgba(201,168,76,0.2)",
        block_label_background_fill="#112240",
        block_label_background_fill_dark="#112240",
        block_label_text_color="#c9a84c",
        block_label_text_color_dark="#c9a84c",
        block_title_text_color="#c9a84c",
        block_title_text_color_dark="#c9a84c",
        button_primary_background_fill="linear-gradient(135deg,#c9a84c,#e8c96a)",
        button_primary_background_fill_dark="linear-gradient(135deg,#c9a84c,#e8c96a)",
        button_primary_text_color="#0a1628",
        button_primary_text_color_dark="#0a1628",
        button_secondary_background_fill="#112240",
        button_secondary_background_fill_dark="#112240",
        button_secondary_border_color="rgba(201,168,76,0.3)",
        button_secondary_border_color_dark="rgba(201,168,76,0.3)",
        button_secondary_text_color="#c9a84c",
        button_secondary_text_color_dark="#c9a84c",
        input_background_fill="#0a1628",
        input_background_fill_dark="#0a1628",
        input_border_color="rgba(201,168,76,0.2)",
        input_border_color_dark="rgba(201,168,76,0.2)",
        input_placeholder_color="#8892a4",
        input_placeholder_color_dark="#8892a4",
        shadow_drop="0 4px 24px rgba(0,0,0,0.4)",
        shadow_drop_lg="0 8px 40px rgba(0,0,0,0.5)",
        table_even_background_fill="#0a1628",
        table_even_background_fill_dark="#0a1628",
        table_odd_background_fill="#112240",
        table_odd_background_fill_dark="#112240",
    )) as demo:

    gr.HTML('<style>::selection{background:#c9a84c;color:#000!important}::-moz-selection{background:#c9a84c;color:#000!important}</style>')
    gr.Markdown("# 🛡️ AI Insurance Arbitration Assistant")
    gr.Markdown("### Powered by [Existential Gateway, LLC](https://existentialgateway.com) | For Insurance Professionals")
    gr.Markdown(DISCLAIMER_TOP)

    with gr.Tabs():

        with gr.Tab("⚖️ Liability"):
            gr.Markdown("## Liability and Accident Reconstructor")
            gr.Markdown(PII_LIAB)
            with gr.Row():
                with gr.Column():
                    liab_loss_state = gr.Dropdown(choices=US_STATES, label="Loss State")
                    liab_intersection = gr.Textbox(label="Intersection", placeholder="Main St and 1st Ave")
                    liab_city = gr.Textbox(label="City", placeholder="Los Angeles")
                    num_vehicles = gr.Dropdown(choices=["2", "3"], value="2", label="Number of Vehicles")
                    traffic_controls = gr.Dropdown(
                        choices=["Traffic Signal (stoplight)", "Stop Sign - Vehicle 1",
                                "Stop Sign - Vehicle 2", "Yield Sign", "No Traffic Controls",
                                "School Zone", "Construction Zone", "Railroad Crossing", "Roundabout"],
                        label="Traffic Controls"
                    )
                with gr.Column():
                    v1_direction = gr.Dropdown(
                        choices=["Northbound", "Southbound", "Eastbound", "Westbound",
                                "Turning Left", "Turning Right", "Parked", "Backing"],
                        label="Vehicle 1 Our Insured Direction"
                    )
                    v1_damage_liab = gr.Textbox(label="Vehicle 1 Damage Areas", placeholder="Front bumper, hood, grille...")
                    v2_direction = gr.Dropdown(
                        choices=["Northbound", "Southbound", "Eastbound", "Westbound",
                                "Turning Left", "Turning Right", "Parked", "Backing"],
                        label="Vehicle 2 Adverse Direction"
                    )
                    v2_damage_liab = gr.Textbox(label="Vehicle 2 Damage Areas", placeholder="Passenger front fender...")
                    v3_direction = gr.Dropdown(
                        choices=["N/A", "Northbound", "Southbound", "Eastbound", "Westbound",
                                "Turning Left", "Turning Right", "Parked", "Backing"],
                        label="Vehicle 3 Direction (if applicable)", value="N/A"
                    )
                    v3_damage_liab = gr.Textbox(label="Vehicle 3 Damage Areas (if applicable)", placeholder="N/A or describe...")

            loss_desc = gr.Textbox(label="Loss Description", placeholder="Describe how the accident occurred...", lines=5)

            with gr.Row():
                with gr.Column():
                    gr.Markdown("### 📄 Document Uploads")
                    police_report = gr.File(label="Police Report (PDF or Image)", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                    liab_doc2 = gr.File(label="Recorded Statement — Insured Party", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                    liab_doc3 = gr.File(label="Recorded Statement — Adverse Party", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                with gr.Column():
                    gr.Markdown("### 📸 Scene and Damage Photos (up to 8)")
                    with gr.Row():
                        photo_l1 = gr.Image(label="Photo 1", type="pil", height=150)
                        photo_l2 = gr.Image(label="Photo 2", type="pil", height=150)
                        photo_l3 = gr.Image(label="Photo 3", type="pil", height=150)
                        photo_l4 = gr.Image(label="Photo 4", type="pil", height=150)
                    with gr.Row():
                        photo_l5 = gr.Image(label="Photo 5", type="pil", height=150)
                        photo_l6 = gr.Image(label="Photo 6", type="pil", height=150)
                        photo_l7 = gr.Image(label="Photo 7", type="pil", height=150)
                        photo_l8 = gr.Image(label="Photo 8", type="pil", height=150)

            gr.Markdown(WAIT_MSG)
            analyze_liab_btn = gr.Button("ANALYZE LIABILITY AND GENERATE CONTENTIONS", variant="primary", size="lg")
            liab_output = gr.Markdown()
            analyze_liab_btn.click(
                fn=analyze_liability,
                inputs=[liab_loss_state, liab_intersection, liab_city,
                        num_vehicles, v1_direction, v1_damage_liab,
                        v2_direction, v2_damage_liab,
                        v3_direction, v3_damage_liab,
                        loss_desc, traffic_controls,
                        photo_l1, photo_l2, photo_l3, photo_l4,
                        photo_l5, photo_l6, photo_l7, photo_l8,
                        police_report, liab_doc2, liab_doc3],
                outputs=liab_output,
                show_progress=True
            )

        with gr.Tab("🔧 Repair Estimate"):
            gr.Markdown("## Repair Estimate Analyzer")
            gr.Markdown(PII_REPAIR)
            with gr.Row():
                with gr.Column():
                    repair_pdf = gr.File(label="Upload Repair Estimate PDF or Image (Optional)", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                    no_estimate = gr.Checkbox(label="No estimate written - Obvious Total Loss (analyze photos only)", value=False)
                    with gr.Row():
                        loss_state_r = gr.Dropdown(choices=US_STATES, label="Loss State")
                        repair_state_r = gr.Dropdown(choices=US_STATES, label="Repair State")
                    with gr.Row():
                        vehicle_year_r = gr.Textbox(label="Year", placeholder="2020")
                        vehicle_make_r = gr.Textbox(label="Make", placeholder="Toyota")
                        vehicle_model_r = gr.Textbox(label="Model", placeholder="Camry")
                with gr.Column():
                    gr.Markdown("### Upload Damage Photos (up to 6)")
                    with gr.Row():
                        photo_r1 = gr.Image(label="Photo 1", type="pil", height=150)
                        photo_r2 = gr.Image(label="Photo 2", type="pil", height=150)
                        photo_r3 = gr.Image(label="Photo 3", type="pil", height=150)
                    with gr.Row():
                        photo_r4 = gr.Image(label="Photo 4", type="pil", height=150)
                        photo_r5 = gr.Image(label="Photo 5", type="pil", height=150)
                        photo_r6 = gr.Image(label="Photo 6", type="pil", height=150)
            gr.Markdown(WAIT_MSG)
            analyze_repair_btn = gr.Button("ANALYZE REPAIR ESTIMATE", variant="primary", size="lg")
            repair_output = gr.Markdown()
            analyze_repair_btn.click(
                fn=analyze_repair_estimate,
                inputs=[repair_pdf, no_estimate,
                        photo_r1, photo_r2, photo_r3,
                        photo_r4, photo_r5, photo_r6,
                        loss_state_r, repair_state_r,
                        vehicle_year_r, vehicle_make_r, vehicle_model_r],
                outputs=repair_output,
                show_progress=True
            )

        with gr.Tab("🚗 Rental Analysis"):
            gr.Markdown("## Rental Bill Analyzer")
            gr.Markdown(PII_RENTAL)
            with gr.Row():
                with gr.Column():
                    rental_pdf = gr.File(label="Upload Rental Bill PDF or Image", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                    repair_pdf_r = gr.File(label="Upload Repair Estimate PDF or Image (Optional)", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                    vehicle_class = gr.Dropdown(choices=VEHICLE_CLASSES, label="Vehicle Class")
                with gr.Column():
                    with gr.Row():
                        loss_state_rent = gr.Dropdown(choices=US_STATES, label="Loss State")
                        repair_state_rent = gr.Dropdown(choices=US_STATES, label="Repair State")
                    repair_start = gr.Textbox(label="Repair Start Date", placeholder="MM/DD/YYYY")
                    repair_end = gr.Textbox(label="Repair End Date", placeholder="MM/DD/YYYY")
            gr.Markdown(WAIT_MSG)
            analyze_rental_btn = gr.Button("ANALYZE RENTAL BILL", variant="primary", size="lg")
            rental_output = gr.Markdown()
            analyze_rental_btn.click(
                fn=analyze_rental,
                inputs=[rental_pdf, repair_pdf_r, vehicle_class,
                        loss_state_rent, repair_state_rent,
                        repair_start, repair_end],
                outputs=rental_output,
                show_progress=True
            )

        with gr.Tab("💰 Total Loss"):
            gr.Markdown("## Total Loss Analyzer")
            gr.Markdown(PII_TL)
            with gr.Row():
                with gr.Column():
                    valuation_pdf = gr.File(label="Upload Valuation Report PDF or Image", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                    estimate_pdf_tl = gr.File(label="Upload Repair Estimate PDF or Image (Optional)", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                with gr.Column():
                    with gr.Row():
                        tl_year = gr.Textbox(label="Year", placeholder="2020")
                        tl_make = gr.Textbox(label="Make", placeholder="Toyota")
                        tl_model = gr.Textbox(label="Model", placeholder="Camry")
                        tl_trim = gr.Textbox(label="Trim", placeholder="LE")
                    tl_mileage = gr.Textbox(label="Mileage", placeholder="45000")
                    tl_loss_date = gr.Textbox(label="Date of Loss", placeholder="MM/DD/YYYY")
                    with gr.Row():
                        tl_loss_state = gr.Dropdown(choices=US_STATES, label="Loss State")
                        tl_zip = gr.Textbox(label="Market Area ZIP", placeholder="90210")
                    tl_condition = gr.Dropdown(choices=["Excellent", "Very Good", "Good", "Fair", "Poor"], label="Vehicle Condition")
            gr.Markdown(WAIT_MSG)
            analyze_tl_btn = gr.Button("ANALYZE TOTAL LOSS", variant="primary", size="lg")
            tl_output = gr.Markdown()
            analyze_tl_btn.click(
                fn=analyze_total_loss,
                inputs=[valuation_pdf, estimate_pdf_tl,
                        tl_year, tl_make, tl_model, tl_trim,
                        tl_mileage, tl_loss_date, tl_loss_state,
                        tl_zip, tl_condition],
                outputs=tl_output,
                show_progress=True
            )

        with gr.Tab("🏥 Bodily Injury"):
            gr.Markdown("## Bodily Injury Analyzer")
            gr.Markdown(PII_BI)
            with gr.Row():
                with gr.Column():
                    medical_pdf = gr.File(label="Upload Medical Records PDF or Image", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                    bi_loss_state = gr.Dropdown(choices=US_STATES, label="Loss State")
                    impact_desc = gr.Textbox(label="Impact Description", lines=3, placeholder="Describe how the accident occurred and severity...")
                    v1_damage_bi = gr.Textbox(label="Vehicle 1 Damage Areas", placeholder="Front, rear, driver side...")
                    v2_damage_bi = gr.Textbox(label="Vehicle 2 Damage Areas", placeholder="Front, rear, passenger side...")
                    impact_speed = gr.Textbox(label="Estimated Impact Speed", placeholder="e.g. 15-20 mph")
                with gr.Column():
                    gr.Markdown("### Upload Impact Photos (up to 4)")
                    with gr.Row():
                        photo_bi1 = gr.Image(label="Photo 1", type="pil", height=150)
                        photo_bi2 = gr.Image(label="Photo 2", type="pil", height=150)
                    with gr.Row():
                        photo_bi3 = gr.Image(label="Photo 3", type="pil", height=150)
                        photo_bi4 = gr.Image(label="Photo 4", type="pil", height=150)
            gr.Markdown(WAIT_MSG)
            analyze_bi_btn = gr.Button("ANALYZE BODILY INJURY", variant="primary", size="lg")
            bi_output = gr.Markdown()
            analyze_bi_btn.click(
                fn=analyze_bodily_injury,
                inputs=[medical_pdf, photo_bi1, photo_bi2, photo_bi3, photo_bi4,
                        bi_loss_state, impact_desc,
                        v1_damage_bi, v2_damage_bi, impact_speed],
                outputs=bi_output,
                show_progress=True
            )

        with gr.Tab("💬 AI Document Chat"):
            gr.Markdown("## AI Insurance Document Chat")
            gr.Markdown("### Chat with your insurance documents! Upload up to 4 PDFs or images and ask any question.")
            gr.Markdown(PII_CHAT)

            with gr.Row():
                with gr.Column(scale=1):
                    gr.Markdown("### Upload Documents (up to 4)")
                    chat_doc1 = gr.File(label="Document 1 (PDF or Image)", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                    chat_doc2 = gr.File(label="Document 2 (PDF or Image)", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                    chat_doc3 = gr.File(label="Document 3 (PDF or Image)", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                    chat_doc4 = gr.File(label="Document 4 (PDF or Image)", file_types=[".pdf", ".jpg", ".jpeg", ".png", ".webp"])
                    chat_context = gr.Textbox(
                        label="Additional Context (optional)",
                        placeholder="e.g. This is a California claim, vehicle is a 2021 Ford Edge...",
                        lines=3
                    )

                with gr.Column(scale=2):
                    chatbot = gr.Chatbot(label="AI Insurance Chat", height=500)
                    with gr.Row():
                        chat_input = gr.Textbox(
                            label="Ask a question about your documents",
                            placeholder="What arbitration contentions can I make based on this estimate?",
                            lines=2,
                            scale=4
                        )
                        send_btn = gr.Button("Send", variant="primary", scale=1)
                    clear_btn = gr.Button("Clear Chat", variant="secondary")
                    gr.Markdown(WAIT_MSG)

            chat_state = gr.State([])

            send_btn.click(
                fn=chat_with_documents,
                inputs=[chat_input, chat_doc1, chat_doc2, chat_doc3, chat_doc4, chat_context],
                outputs=[chatbot, chat_input],
                show_progress=True
            )

            chat_input.submit(
                fn=chat_with_documents,
                inputs=[chat_input, chat_doc1, chat_doc2, chat_doc3, chat_doc4, chat_context],
                outputs=[chatbot, chat_input],
                show_progress=True
            )

            def clear_chat():
                return [], []

            clear_btn.click(fn=clear_chat, outputs=[chatbot, chat_state], show_progress=False)

    gr.Markdown("---")
    gr.Markdown("### © 2026 Existential Gateway, LLC | AI Insurance Arbitration Assistant")
    gr.Markdown("Unauthorized reproduction strictly prohibited. Licensing: existentialgateway@gmail.com | [existentialgateway.com](https://existentialgateway.com)")

demo.launch(
    server_name="0.0.0.0",
    server_port=int(os.environ.get("GRADIO_SERVER_PORT", 7874)),
    share=False,
    ssr_mode=False
)
